import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
            <nav className="bg-gray-800 text-white p-4">
              <div className="container mx-auto flex justify-between items-center">
                <Link href="/" className="text-lg font-bold">
                 DEMO
                </Link>
                <div className="space-x-4">
                  <Link href="/home" className="hover:underline">Home</Link>
                  <Link href="/products" className="hover:underline">Products</Link>
                  <Link href="/dashboard" className="hover:underline">Dashboard</Link>
                  <Link href="/profile/2" className="hover:underline">Profile 2</Link>
                  <Link href="/profile/3" className="hover:underline">Profile 3</Link>
                  <Link href="/api" className="hover:underline">API</Link>
                  <Link href="/api/1" className="hover:underline">API 1</Link>
                  <Link href="/server-component" className="hover:underline">Server Component</Link>
                  {/* <Link href="/simple-dashboard" className="hover:underline">Simple Dashboard</Link>
                  <Link href="/test-login" className="hover:underline">Test Login</Link>
                  <Link href="/login" className="hover:underline">OAuth Login</Link>
                  <Link href="/forgot-password" className="hover:underline">Forgot Password</Link>
                  <Link href="/blog" className="hover:underline">Blog</Link>
                  <Link href="/lambda-test" className="hover:underline">Lambda Test</Link>
                  <Link href="/private" className="hover:underline">Private Route</Link>
                  <Link href="/hello" className="hover:underline">Hello</Link>
                  <Link href="/formatted-date" className="hover:underline">Formatted Date</Link>
                  <Link href="/articles/breaking-news-123?lang=en" className="hover:underline"> Read in English</Link>
                  <Link href="/articles/breaking-news-123?lang=fr" className="hover:underline"> Read in French</Link> */}
                </div>
              </div>
            </nav>
            <main className="container mx-auto p-4">
              {/* <h1 className="text-2xl font-bold mb-4">Welcome to My Next.js App</h1> */}
              {children}
            </main>
            <div className="container mx-auto p-4">
              <h2 className="text-xl font-semibold mb-2">Recent Posts</h2>
              <ul className="list-disc pl-5">
                <li><a href="/blog/first" className="hover:underline">First Blog Post</a></li>
                <li><a href="/blog/second" className="hover:underline">Second Blog Post</a></li>
              </ul>
            </div>

        <footer className="text-center text-sm text-gray-500 mt-8">
              © {new Date().getFullYear()} My Next.js App. All rights reserved.
            </footer>
      </body>
    </html>
  );
}
